# Generated by Django 5.2 on 2025-05-05 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('fertilizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='fertilizers/')),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fungicide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fungus_type', models.CharField(max_length=255)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='GardenFertilizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nitrogen_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='MicroNutri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mineral_type', models.CharField(max_length=255)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicFertilizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pest_type', models.CharField(max_length=255)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='OutdoorPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(max_length=100)),
                ('growth_rate', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='IndoorPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_requirement', models.CharField(max_length=100)),
                ('water_schedule', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='GroundCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread_rate', models.CharField(max_length=100)),
                ('use_case', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('fragrance', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='BonsaiPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nutrients', models.TextField()),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('blooming_time', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='SeedStarter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('use_method', models.CharField(max_length=255)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='WateringSolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=255)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.fertilizer')),
            ],
        ),
    ]
