# Generated by Django 5.2 on 2025-05-06 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0001_initial'),
        ('users_app', '0006_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_cart', to='users_app.cart'),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='fav_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_favorite', to='users_app.favorite'),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_order', to='users_app.order'),
        ),
        migrations.AddField(
            model_name='plant',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_cart', to='users_app.cart'),
        ),
        migrations.AddField(
            model_name='plant',
            name='fav_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_favorite', to='users_app.favorite'),
        ),
        migrations.AddField(
            model_name='plant',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_order', to='users_app.order'),
        ),
    ]
