# Generated by Django 5.2 on 2025-05-06 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0003_seed'),
        ('users_app', '0006_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenTools',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='tools/')),
                ('stock', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.cart')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.favorite')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Pots',
            fields=[
                ('pot_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='pots/')),
                ('stock', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.cart')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.favorite')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.order')),
            ],
        ),
    ]
