# Generated by Django 5.2 on 2025-05-06 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0004_gardentools_pots'),
        ('users_app', '0006_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('soil_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.cart')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.favorite')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Perlite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.CharField(max_length=100)),
                ('application', models.TextField()),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perlite', to='plants_app.soil')),
            ],
        ),
        migrations.CreateModel(
            name='OrganicCompost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compost_type', models.CharField(max_length=100)),
                ('nutrient_level', models.CharField(max_length=100)),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organic_compost', to='plants_app.soil')),
            ],
        ),
        migrations.CreateModel(
            name='SweetSoilRiverSoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('texture', models.CharField(max_length=100)),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweet_soil_river_soil', to='plants_app.soil')),
            ],
        ),
    ]
