# Generated by Django 5.2 on 2025-05-06 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0005_soil_perlite_organiccompost_sweetsoilriversoil'),
        ('users_app', '0006_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenDecoration',
            fields=[
                ('decor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='garden_decorations/')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.cart')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.favorite')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.order')),
            ],
        ),
    ]
