# Generated by Django 5.2 on 2025-05-06 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0006_gardendecoration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('cart_id', models.IntegerField(blank=True, null=True)),
                ('favorite_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(max_length=100)),
                ('soil_preference', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantations', to='plants_app.services')),
            ],
        ),
        migrations.CreateModel(
            name='LawnRestoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawn_condition', models.CharField(max_length=100)),
                ('restoration_method', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawn_restorations', to='plants_app.services')),
            ],
        ),
        migrations.CreateModel(
            name='Landscaping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_size', models.CharField(max_length=100)),
                ('design_type', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landscaping_services', to='plants_app.services')),
            ],
        ),
    ]
