# Generated by Django 5.2 on 2025-05-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0007_services_plantation_lawnrestoration_landscaping'),
        ('users_app', '0006_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.cart'),
        ),
        migrations.AlterField(
            model_name='services',
            name='favorite_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.favorite'),
        ),
        migrations.AlterField(
            model_name='services',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.order'),
        ),
    ]
