# Generated by Django 5.2 on 2025-05-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0008_alter_services_cart_id_alter_services_favorite_id_and_more'),
        ('users_app', '0006_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pebbles',
            fields=[
                ('pebble_id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pebbles/')),
                ('stock', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.cart')),
                ('favorite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.favorite')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.order')),
            ],
        ),
    ]
